import { Geist, Geist_Mono } from "next/font/google";
import { Luckiest_Guy } from "next/font/google";
import "./globals.css";

import { dbConnect } from "@/service/mongoose";

import Navbar from "@/components/navbar/Navbar";
import { getAvatar } from "@/queries/avatar";
import { getSocialLinks } from "@/queries/social";
import { auth } from "@/auth";
import DelayedContent from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const luckiestGuy = Luckiest_Guy({
  weight: "400",
  variable: "--font-luckiest-guy",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
   const avatarData = await getAvatar();
   const links =await getSocialLinks()
      const session = await auth();


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${luckiestGuy.variable} antialiased`}
      >
        <Navbar links={links?.[0]} session={session}  avatarData={avatarData?.[0]}></Navbar>
        <DelayedContent>
 {children}

        </DelayedContent>
       
      </body>
    </html>
  );
}
